spring:
  application:
    name: consumer-movie-ribbon-with-hystrix2
server:
  port: 7802
  context-path: /ribbon
eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    home-page-url: /ribbon
