spring:
  application:
    name: gateway-zuul-fallback
server:
  port: 7502
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
