spring:
  application:
    name: consumer-movie
server:
  port: 7800

user:
  userServicePath: http://localhost:7900/findById/

eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
