spring:
  application:
    name: gateway-zuul
server:
  port: 7500
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /user-path/**
      serviceId: provider-user

ribbon:
  eureka:
    enabled: false

provider-user: #serviceId
  ribbon:
    listOfServers: http://192.168.1.3:7901/,http://192.168.1.3:7902/