spring:
  application:
    name: gateway-zuul-filter
server:
  port: 7500
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    user:
      path: /user-path/**
      serviceId: provider-user
